<?php

/**
 *
 * Flag Pages Module
 *
 * @author Marcus
 * https://github.com/marcus-herrmann/FlagPages
 *
 * @date_created 07/19/2014
 *
 * ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

require_once 'includes/autoload.php';

class FlagPages extends WireData implements Module, ConfigurableModule {

	public static function getModuleInfo() {
		return array(
			"title" => "FlagPages",
			"version" => 011,
			"summary" => "Lets logged-in user flag page content"
		);
	}

	public function __construct() {
		PWModuleConfigHelper::apply($this, self::$defaultConfig);
	}


	public static function getModuleConfigInputfields(array $data) {
		return PWModuleConfigHelper::renderForm($data, self::$defaultConfig);
	}

	protected static $defaultConfig = array(

		// example with just one option
		'prettySetting'  => array(

			// the label for the form
			'label' => 'Pretty Setting',

			// the default value
			'value' => 'I am pretty',

			// optional, defaults to 'InputfieldText'
			'inputfieldType' => 'InputfieldText'
		),

		// example with multiple options
		'awesomeSetting' => array(

			// the label for the form
			'label' => 'Awesome Setting',

			// the default value
			'value' => 2,

			// optional, defaults to 'InputfieldRadios'
			'inputfieldType' => 'InputfieldRadios',

			// each key is for the input label, each value will be saved if selected
			'options' => array(
				'Option 1' => 1,
				'Option 2' => 2,
				'Option 3' => 3
			),

			// set any additional attribute to the input field
			'attributes' => array(
				'optionColumns' => 1
			)
		)
	);


	public function install() {

		/*
		 * Create flaggedpages field and assign it to user template
		 */

		if(!$this->fields->get("flaggedpages")) {

			$f = new Field();
			$f->type = $this->modules->get("FieldtypePage");
			$f->name = "flaggedpages";
			$f->label = "Flagged Pages";
			$f->description = "References to flagged pages " . $this->awesomeSetting["label"];
			$f->save();

			$fg = $this->fieldgroups->get('user');
			$fg->add($f);
			$fg->save();

			$this->message("Module is installed");

		}

	}

	public function uninstall() {

		/*
 		* Delete flaggedpages field
 		*/

		$fp = $this->fields->get("flaggedpages");
		$fg = $this->fieldgroups->get('user');
		$fg->remove($fp);
		$fg->save();
		//$fp->delete(); @TODO delete flaggedpages completely

		$this->message("Module is uninstalled");
	}



	public function renderLink($add, $remove) {

		/*
		 * Render link switch to flag/unflag pages
		 */

		$user = $this->user;
		$input = $this->input;
		$page = $this->page;
		$pages = $this->pages;
		$session = $this->session;
		$userFlaggedPages = $this->user->flaggedpages;

		$add = ($add ? $add : "Add %s to flags");
		$remove = ($remove ? $remove : "Remove %s from flags");

		$addLabel = sprintf($add, $page->title);
		$removeLabel = sprintf($remove, $page->title);

		if ($user->isLoggedin()) {

			$label = ($userFlaggedPages->has($page) ? $removeLabel : $addLabel);

			echo "<a href='{$page->url}?flag={$page->id}'>{$label}</a>";


			if ($input->get("flag")) {
				$p = $input->get("flag");

				$user->setOutputFormatting(false);

				if ($userFlaggedPages->has($pages->get($p))) {
					$userFlaggedPages->remove($pages->get($p));
				} else {
					$userFlaggedPages->add($pages->get($p));
				}

				$user->save();
				$session->redirect($pages->get($p)->url);

			}
		}
	}

	public function renderList() {

		/*
 		 * Provide a list for navigating to, and removing user's flags
 		 */

		$userFlaggedPages = $this->user->flaggedpages;


		if ($this->user->isLoggedin() && $userFlaggedPages) {

			echo "<ul>";

			foreach($userFlaggedPages as $f) {
				echo "<li><a href='" . $f->url . "'>" . $f->title . "</a></li>";
			}

			echo "</ul>";
		}

	}

	public function init() {}


}
