<?php

/**
 *
 * Flag Pages Module
 *
 * @author Marcus
 * https://github.com/marcus-herrmann/FlagPages
 *
 * @date_created 07/19/2014
 *
 * ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class FlagPages extends WireData implements Module {

	public static function getModuleInfo() {
		return array(
			"title" => "FlagPages",
			"version" => 011,
			"summary" => "Lets logged-in user flag page content",
			"autoload" => false,
			"singular" => true
		);
	}

	public static function getModuleConfigInputfields(array $data) {
		$fields = new InputfieldWrapper();

		$modules = wire('modules');

		$field = $modules->get("InputfieldText");
		$field->attr('name', 'flaggingUserRoles');
		$field->attr('value', $data['flaggingUserRoles']);
		$field->label = "User roles that are allowed to flag";
		$field->description = "";
		$fields->add($field);

		return $fields;

	}

	public function install() {

		/*
		 * Create flaggedpages field and assign it to user template
		 */

		$f = new Field();
		$f->type = $this->modules->get("FieldtypePage");
		$f->name = "flaggedpages";
		$f->label = "Flagged Pages";
		$f->description = "References to flagged pages ";
		$f->save();

		$fg = $this->fieldgroups->get('user');
		$fg->add($f);
		$fg->save();

		$this->message("Module is installed");

	}

	public function uninstall() {

		/*
 		* Delete flaggedpages field
 		*/

		$fp = $this->fields->get("flaggedpages");
		$fg = $this->fieldgroups->get('user');
		$fg->remove($fp);
		$fg->save();
		//$fp->delete(); @TODO delete flaggedpages completely

		$this->message("Module is uninstalled");
	}



	public function renderLink($add, $remove) {

		/*
		 * Render link switch to flag/unflag pages
		 */

		$user = $this->user;
		$input = $this->input;
		$page = $this->page;
		$pages = $this->pages;
		$session = $this->session;
		$userFlaggedPages = $this->user->flaggedpages;

		$add = ($add ? $add : "Add %s to flags");
		$remove = ($remove ? $remove : "Remove %s from flags");

		$addLabel = sprintf($add, $page->title);
		$removeLabel = sprintf($remove, $page->title);

		if ($user->isLoggedin()) {

			$label = ($userFlaggedPages->has($page) ? $removeLabel : $addLabel);

			echo "<a href='{$page->url}?flag={$page->id}'>{$label}</a>";


			if ($input->get("flag")) {
				$p = $input->get("flag");

				$user->setOutputFormatting(false);

				if ($userFlaggedPages->has($pages->get($p))) {
					$userFlaggedPages->remove($pages->get($p));
				} else {
					$userFlaggedPages->add($pages->get($p));
				}

				$user->save();
				$session->redirect($pages->get($p)->url);

			}
		}
	}

	public function renderList() {

		/*
 		 * Provide a list for navigating to, and removing user's flags
 		 */

		$userFlaggedPages = $this->user->flaggedpages;


		if ($this->user->isLoggedin() && $userFlaggedPages) {

			echo "<ul>";

			foreach($userFlaggedPages as $f) {
				echo "<li><a href='" . $f->url . "'>" . $f->title . "</a></li>";
			}

			echo "</ul>";
		}

	}

	public function init() {}

}
